intent_dict = {
    'greet and hello hi kind of things, general check in': ['hi', 'hello', 'hey', 'howdy', 'hi how are you', 'whats up',
                                                            'hey there', 'hello there', 'hey there',
                                                            'hello there', 'hi there'],
    'goodbye': ['bye', 'good bye', 'good morning', 'good afternoon', 'good evening', 'good day',
                'good night', 'good day', 'good evening', 'see you later', 'see you'],
    'asking date': ['date', 'today', 'tomorrow', 'day after tomorrow', 'day before tomorrow',
                    'what day is it', 'what is the date', 'what is the day', 'what is the day of the week',
                    'what day is it today',
                    'what day is it tomorrow', 'what day is it day after tomorrow',
                    'what day is it day before tomorrow'],
    'asking time': ['time', 'what time is it', 'what is the time', 'what is the time now', 'what time is it now',
                    'what time is it today', 'what time is it tomorrow', 'what time is it day after tomorrow',
                    'what time is it day before tomorrow'],
    'asking weather': ['weather', 'what is the weather', 'what is the weather today', 'what is the weather tomorrow',
                       'what is the weather day after tomorrow', 'what is the weather day before tomorrow',
                       'what is the weather like', 'what is the weather like today',
                       'what is the weather like tomorrow', 'what is the weather like day after tomorrow',
                       'what is the weather like day before tomorrow',
                       'what is the weather like now', 'what is the weather like now today',
                       'what is the weather like now tomorrow', 'what is the weather like now day after tomorrow',
                       'what is the weather like now day before tomorrow', 'What is the weather like today',
                       'Will it rain tomorrow', 'How hot will it be', 'Is it going to snow'],
    'tell me joke': ['tell me a joke', 'tell me a joke today', 'tell me a joke about donal trump',
                     'tell me a joke about xenophobia', 'tell me a joke about trump and xi',
                     'tell me a joke about getting a first', 'tell me a joke about virginia',
                     'tell me a joke about asia', 'tell me a joke about the moon', 'tell me a joke about the sun',
                     'tell me joke about trump', 'tell me a joke about the north korea nuclear summit',
                     'tell me a joke about kim jong un', 'tell me fun joke', 'tell me a dad joke', 'tell me a fun joke',
                     'tell me a dad joke', 'tell me a dad joke', 'tell me a fun joke', 'make me laugh'],
    'tell me news': ['tell me news', 'tell me news today', 'tell me news tomorrow',
                     'tell me news day after tomorrow', 'tell me news day before tomorrow',
                     "what is the update on stock market", "what's going on in the world",
                     "what's going on with economy", "tell me the news", "tell me the news of the day",
                     "what's good news today", "what's good news", "tell me good news", "what's the good news",
                     "please tell me good news," "tell me some good news," "tell me something good happened",
                     "what's the good news?", "tell me what good news", "what's good", "I have good news",
                     "I have some great news for you", "what's the good news of stock market", "good news for economy"],
    'tell me about': ['tell me about', 'tell me about today', 'tell me about tomorrow', 'tell me about taj mahal',
                      'tell me about president', 'tell me about president of india', 'tell me about president of usa',
                      'where is kenya', 'tell me about history of british india', 'tell me about my baby',
                      'tell me about my family', 'tell me about my day', 'tell me about my college',
                      'tell me about my job', 'tell me about my business', 'tell me about my day',
                      'tell me about my life', 'tell me about my day',
                      'tell me about a vet', 'tell me about yours', 'tell me about my day', 'tell me about my day',
                      'tell me about my world', 'tell me you', 'Can you tell me about', 'What is the', 'How do I',
                      'I am looking for', 'Where can I find', 'Tell me about'],
    'open website': ['open website facebook.com', 'open website google.com', 'open website youtube.com',
                     'open website wikipedia.com', 'open website twitter.com', 'open website instagram.com',
                     'open website linkedin.com', 'open website stackoverflow.com', 'open website github.com',
                     'open website quora.com', 'open website stackoverflow.com', 'open website stackoverflow.com'],
    'play on youtube': ['play on youtube', 'play shape of you on youtube today', 'play despacito on youtube today',
                        'play <song> on youtube', 'play guru randhawa on youtube', 'play let me love you on youtube',
                        'play bad guy on youtube', 'play kishore kumar on youtube'],
    'send whatsapp message': ['send whatsapp message', 'send whatsapp message to', 'send whatsapp message to <name>',
                              'send whatsapp message to 9898982565', 'send whatsapp message to dipesh',
                              'send whatsapp message about', 'send whatsapp message about <name>'],
    'send email': ['send email', 'send email to', 'send email to <name>', 'send email to dipesh',
                   'send email about', 'send email about <name>', 'send email to <name> about <name>',
                   'send email to xyz@gmail.com'],
    'take screenshot': ['take screenshot', 'take screenshot of', 'take screenshot of <name>',
                        'take screenshot of google',
                        'screen shot', 'screen shot of', 'screen shot of <name>', 'screen shot now'],
    'click photo': ['click photo', 'click photo of', 'click photo of <name>', 'click selfie', 'click selfie of',
                    'capture photo', 'capture photo of', 'capture photo of <name>', 'capture selfie',
                    'capture selfie of'],
    'check internet speed': ['check internet speed', 'check internet speed of', 'check internet speed of chrome',
                             'check internet speed of firefox', 'check internet speed of <name>',
                             'check internet speed of edge', 'check internet speed of safari',
                             'check internet speed of opera', 'check internet speed of ie',
                             'check internet speed of chrome 64', 'check internet speed of firefox 64'],
    'covid cases': ['covid cases', 'covid cases of', 'covid cases of india', 'covid cases of india past 24 hours',
                    'covid cases of india past 48 hours', 'daily cases', 'daily cases of', 'daily cases of india',
                    'covid confirmed cases', 'covid confirmed cases of'],
    'play games': ['play games', 'play games with me', 'play mario', 'play pacman game with me',
                   'play games of xyz 32 bit', 'play games of xyz 64 bit',
                   'play games of busybox', 'play games of c', 'play games of gcc',
                   'play games of xxd', 'play baseball', 'play baseball with me', 'play baseball net', 'play football',
                   'play minecraft', 'play minecraft with me'],
    'download youtube video': ['download youtube video', 'download youtube video of',
                               'download youtube video of <name>',
                               'download youtube video of guru randhawa', 'download youtube video of <name> today',
                               'download youtube video of minecraft', 'download youtube video of kishore kumar',
                               'download youtube video hd', 'download youtube video hd of'],
    'what can you do': ['what can you do',
                        'what can you do for me',
                        'what can you do for me today',
                        'What can you help me with?',
                        'What are your capabilities?',
                        'What services do you offer?',
                        'What actions can you perform?',
                        'What are your functions?',
                        'What tasks can you complete?',
                        'What can you assist me with?',
                        'What can I ask you to do?',
                        'What are the things you can do?',
                        'What are your functionalities?',
                        ],
    'volume control': ['volume control',
                       'volume control up',
                       'volume control down',
                       'volume control mute',
                       'volume control unmute',
                       'volume control increase',
                       'volume control decrease',
                       'volume control increase by 10',
                       'volume control decrease by 10',
                       'Can you increase the volume?',
                       'Can you lower the volume?',
                       'Can you turn the volume up?',
                       'Can you turn the volume down?',
                       'Can you set the volume to maximum?',
                       'Can you set the volume to minimum?',
                       'Can you mute the volume?',
                       'Can you change the volume to a specific level?',
                       'Can you adjust the volume?',
                       'Can you control the volume?'],
    'i am bored': ['i am bored', 'i am bored today', 'i am bored today what can i do', 'i am bored what can i do',
                   'i am bored what can i do today', 'i am bored what can i do today with my friends',
                   'i am bored what can i do today with my family', 'i am bored what can i do today with my girlfriend',
                   'i am bored what can i do today with my boyfriend', 'i am bored what can i do today with my wife',
                   "I am so bored",
                   "I am really bored",
                   "I have nothing to do",
                   "I am feeling bored",
                   "I am finding myself bored",
                   "I am getting bored",
                   "I am feeling a bit bored",
                   "I am finding this boring",
                   "I am not entertained",
                   "I am feeling unoccupied"],
    'places near me': ['places near me', 'places near me to eat', 'places near me to eat today',
                       'places near me to eat today with my friends', 'places near me to eat today with my family',
                       "What are some places near me?",
                       "Can you recommend some places nearby?",
                       "Where can I find something nearby?",
                       "What are the closest places to me?",
                       "I am looking for places around here",
                       "Can you tell me the best places nearby?",
                       "Where should I go nearby?",
                       "What are some nearby locations?",
                       "Can you suggest some nearby places to visit?",
                       "What are the top places nearby?"],

}
